---
title: "Task 2: Reading Delimited Data"
format: html
toc: TRUE
editor_options: 
  chunk_output_type: console
---

## Load readr and dplyr packages:

```{r}
library(readr)
library(dplyr)
```

## Glass Data

1.  Read in data:

```{r}
glass_data <- read_csv("https://www4.stat.ncsu.edu/online/datasets/glass.data", 
         col_names = c("Id", "RI", "Na", "Mg", "Al", "Si", "K", "Ca", "Ba", "Fe", "Type_of_Glass"))
glass_data
```

2.  Start a Chain to Mutate Type_of_Glass column:

3.  Continue Chain to Filter Data:

```{r}
glass_data <- glass_data |>
  mutate(Type_of_Glass = ifelse(Type_of_Glass == 1, 
                                "building_windows_float_processed",
                                ifelse(Type_of_Glass == 2, 
                                       "building_windows_non_float_processed", 
                                       ifelse(Type_of_Glass == 3, 
                                              "vehicle_windows_float_processed",
                                              ifelse(Type_of_Glass == 4, 
                                                     "vehicle_windows_non_float_processed",
                                                     ifelse(Type_of_Glass == 5,
                                                            "containers",
                                                            ifelse(Type_of_Glass == 6,
                                                                   "tableware",
                                                                   ifelse(Type_of_Glass == 7, 
                                                                          "headlamps", 
                                                                          "error")))))))) |>
  filter(Fe < 0.2, Type_of_Glass %in% c("tableware", "headlamps"))
glass_data
```

## Yeast Data

1.  Read in Data:

```{r}
yeast_data <- read_fwf("https://www4.stat.ncsu.edu/online/datasets/yeast.data",
                       fwf_widths(c(12, 6, 6, 6, 6, 6, 6, 6, 6, 3),
                                  col_names = c("seq_name", "mcg", "gvh", "alm", "mit", "erl", "pox", "vac", "nuc", "class")))
yeast_data
```

2.  Start a Chain to Remove Specified Columns:

3.  Continue Chain to Add Specified Columns:

```{r}
yeast_data <- yeast_data |>
  select(!c(seq_name, nuc)) |>
  group_by(class) |>
  mutate(across((mcg:vac), list(mean = mean, median = median), .names = "{.col}_{.fn}"))
yeast_data

```
